# Generated by Django 3.2.3 on 2021-05-24 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extra_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('weight_info', models.CharField(max_length=100)),
                ('packaging_info', models.CharField(max_length=100)),
                ('packaging_type', models.CharField(choices=[('TN', 'Tin'), ('PT', 'Packet'), ('ST', 'Sachet')], max_length=2)),
                ('expired_on', models.DateTimeField()),
                ('is_frozen', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(editable=False)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
