# Generated by Django 3.2.3 on 2021-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_item_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired_on',
            field=models.DateField(),
        ),
    ]
