# Generated by Django 3.2.3 on 2021-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_expired_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
